name: TEST111

on:
  push:

  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest

    steps:
      - run: echo "TEST TEST"

      - uses: actions/checkout@v4

      - run: |
          ls -la
          cd .github/workflows/
          ls -la